services:
  - type: web
    name: walkie-talkie
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NO_HTTPS
        value: true
      - key: MONGODB_URI
        sync: false
